-- MySQL Script generated by MySQL Workbench
-- Wed Sep 13 10:53:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema processoseletivo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema processoseletivo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `processoseletivo` DEFAULT CHARACTER SET utf8 ;
USE `processoseletivo` ;

-- -----------------------------------------------------
-- Table `processoseletivo`.`emissor_rg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`emissor_rg` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `nome_pai` VARCHAR(45) NOT NULL,
  `nome_mae` VARCHAR(45) NOT NULL,
  `estrangeira` TINYINT NULL,
  `escolaridade_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  `passaporte` VARCHAR(45) NOT NULL,
  `emissor_rg_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pessoa_id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_pessoa_emissor_rg1_idx` (`emissor_rg_id` ASC),
  CONSTRAINT `fk_pessoa_emissor_rg1`
    FOREIGN KEY (`emissor_rg_id`)
    REFERENCES `processoseletivo`.`emissor_rg` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estado_pais1_idx` (`pais_id` ASC),
  CONSTRAINT `fk_estado_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `processoseletivo`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `estado_id` INT NOT NULL,
  `naturalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado1_idx` (`estado_id` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `processoseletivo`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`tipo_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`tipo_endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `pessoa_id` INT NOT NULL,
  `cidade_id` INT NOT NULL,
  `tipo_endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enderco_pessoa_idx` (`pessoa_id` ASC),
  INDEX `fk_endereco_cidade1_idx` (`cidade_id` ASC),
  INDEX `fk_endereco_tipo_endereco1_idx` (`tipo_endereco_id` ASC),
  CONSTRAINT `fk_enderco_pessoa`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `processoseletivo`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `processoseletivo`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_tipo_endereco1`
    FOREIGN KEY (`tipo_endereco_id`)
    REFERENCES `processoseletivo`.`tipo_endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`tipo_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`tipo_telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoa_id` INT NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `tipo_telefone_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_telefone_pessoa1_idx` (`pessoa_id` ASC),
  INDEX `fk_telefone_tipo_telefone1_idx` (`tipo_telefone_id` ASC),
  CONSTRAINT `fk_telefone_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `processoseletivo`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefone_tipo_telefone1`
    FOREIGN KEY (`tipo_telefone_id`)
    REFERENCES `processoseletivo`.`tipo_telefone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`usuario` (
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `pessoa_id` INT NOT NULL,
  PRIMARY KEY (`pessoa_id`),
  INDEX `fk_login_pessoa1_idx` (`pessoa_id` ASC),
  CONSTRAINT `fk_login_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `processoseletivo`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`tipo_processo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`tipo_processo` (
  `id` INT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`processo_seletivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`processo_seletivo` (
  `id` INT NULL AUTO_INCREMENT,
  `data_inicio` DATETIME NOT NULL,
  `data_final` DATETIME NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tipo_processo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_processo_seletivo_tipo_processo1_idx` (`tipo_processo_id` ASC),
  CONSTRAINT `fk_processo_seletivo_tipo_processo1`
    FOREIGN KEY (`tipo_processo_id`)
    REFERENCES `processoseletivo`.`tipo_processo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`cota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`cota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`inscricao` (
  `pessoa_id` INT NOT NULL,
  `data_pagamento` DATE NOT NULL,
  `data_inscricao` DATE NOT NULL,
  `processo_seletivo_id` INT NOT NULL,
  `primeira_opcao` INT NOT NULL,
  `cota_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `segunda_opcao` INT NULL,
  INDEX `fk_inscricao_pessoa1_idx` (`pessoa_id` ASC),
  INDEX `fk_inscricao_processo_seletivo1_idx` (`processo_seletivo_id` ASC),
  INDEX `fk_inscricao_cursos1_idx` (`primeira_opcao` ASC),
  INDEX `fk_inscricao_cota1_idx` (`cota_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `fk_inscricao_cursos2_idx` (`segunda_opcao` ASC),
  CONSTRAINT `fk_inscricao_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `processoseletivo`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscricao_processo_seletivo1`
    FOREIGN KEY (`processo_seletivo_id`)
    REFERENCES `processoseletivo`.`processo_seletivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscricao_cursos1`
    FOREIGN KEY (`primeira_opcao`)
    REFERENCES `processoseletivo`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscricao_cota1`
    FOREIGN KEY (`cota_id`)
    REFERENCES `processoseletivo`.`cota` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscricao_cursos2`
    FOREIGN KEY (`segunda_opcao`)
    REFERENCES `processoseletivo`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`escolaridade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`tipo_escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`tipo_escolaridade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_escolaridade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`pessoa_escolaridade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`pessoa_escolaridade` (
  `pessoa_id` INT NOT NULL,
  `escolaridade_id` INT NOT NULL,
  `tipo_escolaridade_id` INT NOT NULL,
  INDEX `fk_pessoa_escolaridade_pessoa1_idx` (`pessoa_id` ASC),
  INDEX `fk_pessoa_escolaridade_escolaridade1_idx` (`escolaridade_id` ASC),
  INDEX `fk_pessoa_escolaridade_tipo_escolaridade1_idx` (`tipo_escolaridade_id` ASC),
  CONSTRAINT `fk_pessoa_escolaridade_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `processoseletivo`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_escolaridade_escolaridade1`
    FOREIGN KEY (`escolaridade_id`)
    REFERENCES `processoseletivo`.`escolaridade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_escolaridade_tipo_escolaridade1`
    FOREIGN KEY (`tipo_escolaridade_id`)
    REFERENCES `processoseletivo`.`tipo_escolaridade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`notificacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`usuario_notificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`usuario_notificacao` (
  `usuario_pessoa_id` INT NOT NULL,
  `notificacao_id` INT NOT NULL,
  INDEX `fk_usuario_notificacao_usuario1_idx` (`usuario_pessoa_id` ASC),
  INDEX `fk_usuario_notificacao_notificacao1_idx` (`notificacao_id` ASC),
  CONSTRAINT `fk_usuario_notificacao_usuario1`
    FOREIGN KEY (`usuario_pessoa_id`)
    REFERENCES `processoseletivo`.`usuario` (`pessoa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_notificacao_notificacao1`
    FOREIGN KEY (`notificacao_id`)
    REFERENCES `processoseletivo`.`notificacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`necessidade_especiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`necessidade_especiais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`pessoa_necessidade_especiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`pessoa_necessidade_especiais` (
  `permanete` TINYINT NOT NULL,
  `observacao` TEXT(200) NOT NULL,
  `pessoa_id` INT NOT NULL,
  `necessidade_especiais_id` INT NOT NULL,
  INDEX `fk_pessoa_necessidade_especiais_pessoa1_idx` (`pessoa_id` ASC),
  INDEX `fk_pessoa_necessidade_especiais_necessidade_especiais1_idx` (`necessidade_especiais_id` ASC),
  CONSTRAINT `fk_pessoa_necessidade_especiais_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `processoseletivo`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_necessidade_especiais_necessidade_especiais1`
    FOREIGN KEY (`necessidade_especiais_id`)
    REFERENCES `processoseletivo`.`necessidade_especiais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`taxas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`taxas` (
  `valor` VARCHAR(45) NOT NULL,
  `vencimento_boleto` DATE NOT NULL,
  `processo_seletivo_id` INT NOT NULL,
  INDEX `fk_taxas_processo_seletivo1_idx` (`processo_seletivo_id` ASC),
  CONSTRAINT `fk_taxas_processo_seletivo1`
    FOREIGN KEY (`processo_seletivo_id`)
    REFERENCES `processoseletivo`.`processo_seletivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`comissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`comissao` (
  `pessoa_id` INT NULL AUTO_INCREMENT,
  `processo_seletivo_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pessoa_id`, `processo_seletivo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`isencoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`isencoes` (
  `motivo` TEXT(200) NOT NULL,
  `homologada` TINYINT NOT NULL,
  `comissao_pessoa_id` INT NOT NULL,
  `comissao_processo_seletivo_id` VARCHAR(45) NOT NULL,
  `inscricao_id` INT NOT NULL,
  INDEX `fk_isencoes_comissao1_idx` (`comissao_pessoa_id` ASC, `comissao_processo_seletivo_id` ASC),
  INDEX `fk_isencoes_inscricao1_idx` (`inscricao_id` ASC),
  PRIMARY KEY (`inscricao_id`),
  CONSTRAINT `fk_isencoes_comissao1`
    FOREIGN KEY (`comissao_pessoa_id` , `comissao_processo_seletivo_id`)
    REFERENCES `processoseletivo`.`comissao` (`pessoa_id` , `processo_seletivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_isencoes_inscricao1`
    FOREIGN KEY (`inscricao_id`)
    REFERENCES `processoseletivo`.`inscricao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
